### ISSUE TITLE
Set up gem structure

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/clinic_finder#1]

**Comment by colinxfleming** [comment]
@lwaldsc it looks like there's a decent tutorial here for how to rig up the structure -- http://guides.rubygems.org/make-your-own-gem/#your-first-gem 

Do you want to run thru it? You can skip the part about 'adding an executable', and the part about pushing to rubygems, but the rest we can do as is.

**Comment by lwaldsc** [comment]
kaaaaaaaaaaaaaaayyyyyy

feeling a bit like i'm randomly stabbing the cans with the opener but can't
learn until you try!

**Comment by colinxfleming** [comment]
Nbd if you can't drive it home, we can work on it together when I'm by a
computer next

**Comment by lwaldsc** [comment]
I'm assuming youre not in much rush considering you gave it to me, but I
have some time on the train to new york tomorrow so if I don't figure it
out tonight, I can continue it then too.

**Comment by colinxfleming** [comment]
100% no rush. If you get packed on it for more than like 15 min let's pick
it up tomorrow when we can do some pairing on it

**Comment by colinxfleming** [comment]
thanks a ton @lwaldsc !
